---
- name: Attempting to generate temporary file
  tempfile:
    prefix: 'elrepo.'
    state: file
    suffix: '.rpm'
  register: elrepo_tempfile

- name: Attempting to download package to temporary location
  get_url:
    dest: "{{ elrepo_tempfile.path }}"
    force: yes
    url: "https://www.elrepo.org/elrepo-release-{{ elrepo_version[elrepo_dist] }}.elrepo.noarch.rpm"
  register: elrepo_get_url
  when: elrepo_tempfile is success

- name: Ensure that the elrepo gpg keys are installed
  rpm_key:
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    state: present

- name: Ensure that the elrepo-release package is installed
  become: true
  yum:
    disable_plugin: "{{ elrepo_disable_plugin|join(',')|default([],true) }}"
    disablerepo: "{{ elrepo_disablerepo|join(',')|default([],true) }}"
    enable_plugin: "{{ elrepo_enable_plugin|join(',')|default([],true) }}"
    enablerepo: "{{ elrepo_enablerepo|join(',')|default([],true) }}"
    name: "{{ elrepo_tempfile.path }}"
    state: present
  register: elrepo_yum
  when: elrepo_get_url is success

- name: Attempting to purge temporary package from the filesystem
  file:
    path: "{{ elrepo_tempfile.path }}"
    state: absent
  when:
    - elrepo_tempfile is success
    - elrepo_yum is success

- name: Attempting to overlay elrepo repository configurations
  become: true
  template:
    src: elrepo.repo.j2
    dest: /etc/yum.repos.d/elrepo.repo
    owner: root
    group: root
    mode: 0644
  when: elrepo_yum is success

- name: Ensure that the required elrepo packages are installed
  become: true
  yum:
    disable_plugin: "{{ elrepo_disable_plugin|join(',')|default([],true) }}"
    disablerepo: "{{ elrepo_disablerepo|join(',')|default([],true) }}"
    enable_plugin: "{{ elrepo_enable_plugin|join(',')|default([],true) }}"
    enablerepo: "{{ elrepo_enablerepo|join(',')|default([],true) }}"
    name: "{{ item }}"
    state: present
  loop: "{{ elrepo_packages }}"
  loop_control:
    label: "{{ item }}"
  when:
    - elrepo_packages|length > 0
    - elrepo_yum is success
...
